src/Entity/Car.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CarRepository")
 */
class Car
{
    const DIESEL = 0;
    const BENSIN = 1;
    const HYBRID = 2;
    const ELECTRIC = 3;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $make;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $model;

    /**
     * @ORM\Column(type="integer")
     */
    private $type;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Trip", mappedBy="cars")
     */
    private $trips;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Driver", mappedBy="cars")
     */
    private $drivers;

    public function __construct()
    {
        $this->drivers = new ArrayCollection();
        $this->trips = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getMake()
    {
        return $this->make;
    }

    /**
     * @param mixed $make
     */
    public function setMake($make): void
    {
        $this->make = $make;
    }

    /**
     * @return mixed
     */
    public function getModel()
    {
        return $this->model;
    }

    /**
     * @param mixed $model
     */
    public function setModel($model): void
    {
        $this->model = $model;
    }

    /**
     * @return mixed
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * @param mixed $type
     */
    public function setType($type): void
    {
        $this->type = $type;
    }

    public function getTypeString()
    {
        switch($this->getType()){
            case self::DIESEL:
                return 'Diesel';
            case self::BENSIN:
                return 'Bensin';
                case self::HYBRID:
                return 'Hybrid';
                case self::ELECTRIC:
                return 'Electric';
        }
    }

    /**
     * @return mixed
     */
    public function getTrips()
    {
        return $this->trips;
    }

    /**
     * @return mixed
     */
    public function getDrivers()
    {
        return $this->drivers;
    }

    public function addDriver(Driver $driver)
    {
        if($this->drivers->contains($driver)){
            return;
        }

        $driver->addCar($this);
        $this->drivers[] = $driver;
    }

    public function removeDriver(Driver $driver)
    {
        if(! $this->drivers->contains($driver)){
            return;
        }

        $driver->removeCar($this);
        $this->drivers->removeElement($driver);
    }
}

src/Form/CarType.php
<?php

namespace App\Form;

use App\Entity\Car;
use App\Entity\Driver;
use App\Repository\CarRepository;
use App\Repository\DriverRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CarType extends AbstractType
{
    private $carRepository;
    /**
     * @var DriverRepository
     */
    private $driverRepository;

    public function __construct(CarRepository $carRepository, DriverRepository $driverRepository)
    {
        $this->carRepository = $carRepository;
        $this->driverRepository = $driverRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('make')
            ->add('model')
            ->add('type', ChoiceType::class, [
                'choices' => [
                    'Diesel' => Car::DIESEL,
                    'Bensin' => Car::BENSIN,
                    'Hybrid' => Car::HYBRID,
                    'Electric' => Car::ELECTRIC,
                ]
            ])
            ->add('drivers', EntityType::class, [
                'class' => Driver::class, 'by_reference' => false, 'choice_label' => "name", 'multiple' => true, 'choices' => $this->driverRepository->findAll()
            ])
            ->add('save', SubmitType::class);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/CarController.php
<?php

namespace App\Controller;

use App\Entity\Car;
use App\Entity\Driver;
use App\Form\CarType;
use App\Repository\CarRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class CarController extends Controller
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var CarRepository
     */
    private $carRepository;

    public function __construct(EntityManagerInterface $entityManager, CarRepository $carRepository)
    {
        $this->entityManager = $entityManager;
        $this->carRepository = $carRepository;
    }

    /**
     * @Route("/car", name="car")
     */
    public function index()
    {
        $cars = $this->carRepository->findAll();
        return $this->render('car/index.html.twig', [
            'controller_name' => 'CarController',
            'cars' => $cars
        ]);
    }

    /**
     * @Route("/car/create", name="car.create")
     */
    public function create(Request $request)
    {
        $car = new Car();
        $form = $this->createForm(CarType::class, $car);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $data = $form->getData();
            $this->entityManager->persist($data);
            $this->entityManager->flush();
        }
        return $this->render('car/create.html.twig', ['form' => $form->createView()
        ]);
    }

    /**
     * @Route ("/car/{id}/edit", name="car.edit")
     */
    public function edit($id, Request $request)
    {
        $car = $this->carRepository->find($id);
        if ($car === null) {
            throw $this->createNotFoundException("Car #{$id} does not exist.");
        }

        $form = $this->createForm(CarType::class, $car);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Car $data */
            $data = $form->getData();

            $this->entityManager->persist($data);
            $this->entityManager->flush();

            return $this->redirect('/car');
        }

        return $this->render('car/create.html.twig', ['form' => $form->createView()
        ]);
    }

    /**
     * @Route ("/car/{id}/delete", name="car.delete")
     */
    public function delete($id)
    {
        $car = $this->carRepository->find($id);
        $this->entityManager->remove($car);
        $this->entityManager->flush();
        return $this->redirect('/car');
    }

}

templates/car/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                {{ form_start(form) }}
                <div class="form-group">
                    {{ form_label(form.make) }}
                    <div class="form-control">
                        {{ form_widget(form.make, {attr: {class: 'form-control'}}) }}
                    </div>
                    {{ form_errors(form.make) }}
                    {{ form_label(form.model) }}
                    <div class="form-control">
                        {{ form_widget(form.model, {attr: {class: 'form-control'}}) }}
                    </div>
                    {{ form_label(form.type) }}
                    <div class="form-control">
                        {{ form_widget(form.type, {attr: {class: 'form-control'}}) }}
                    </div>
                    <div class="form-control">
                            {{ form_widget(form.drivers, {attr: {class: 'form-control'}}) }}
                    </div>
                    <div class="form-control">
                        {{ form_widget(form.save,  {attr: {class: 'form-control btn btn-success'}}) }}
                    </div>
                    {{ form_end(form) }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/car/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="container">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Make</th>
                            <th>Model</th>
                            <th>Type</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for car in cars %}
                            <tr>
                                <td>{{ car.id }}</td>
                                <td>{{ car.make }}</td>
                                <td>{{ car.model }}</td>
                                <td>{{ car.typeString }}</td>
                                <td><a href="{{ path('car.edit', {id: car.id}) }}">Edit</a></td>
                                <td><a href="{{ path('car.delete', {id: car.id}) }}">Delete</a></td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                <a class="btn btn-warning" href="{{ 'car/create' }}">Create car</a>
            </div>
        </div>
    </div>
{% endblock %}