src/Entity/Client.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ClientRepository")
 */
class Client
{
    const MALE = 0;
    const FEMALE = 1;
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $gender;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Trip", mappedBy="client")
     */
    private $trips;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return mixed
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * @param mixed $name
     */
    public function setName($name): void
    {
        $this->name = $name;
    }

    public function getGender()
    {
        return $this->gender;
    }

    /**
     * @param mixed $gender
     */
    public function setGender($gender): void
    {
        $this->gender = $gender;
    }

    public function getGenderString()
    {
        switch($this->getGender()){
            case self::MALE:
                return 'Male';
            case self::FEMALE:
                return 'Female';
        }
    }

    /**
     * @return Trip[]
     */
    public function getTrips()
    {
        return $this->trips;
    }
}

src/Form/ClientType.php
<?php

namespace App\Form;

use App\Entity\Client;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('gender', ChoiceType::class, [
                'choices' => [
                    'Male' => Client::MALE,
                    'Female' => Client::FEMALE,
                ]
            ])
            ->add('save', SubmitType::class);
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            // Configure your form options here
        ]);
    }
}

src/Controller/ClientController.php
<?php

namespace App\Controller;

use App\Entity\Client;
use App\Form\ClientType;
use App\Repository\ClientRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class ClientController extends Controller
{
    /**
     * @var EntityManagerInterface
     */
    private $entityManager;
    /**
     * @var ClientRepository
     */
    private $clientRepository;

    public function __construct(EntityManagerInterface $entityManager, ClientRepository $clientRepository)
    {
        $this->entityManager = $entityManager;
        $this->clientRepository = $clientRepository;
    }

    /**
     * @Route("/client", name="client")
     */
    public function index()
    {
        $clients = $this->clientRepository->findAll();
        return $this->render('client/index.html.twig', [
            'controller_name' => 'ClientController',
            'clients' => $clients
        ]);
    }

    /**
     * @Route("/client/create", name="client.create")
     */
    public function create(Request $request)
    {
        $client = new Client();
        $form = $this->createForm(ClientType::class, $client);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $data = $form->getData();
            $this->entityManager->persist($data);
            $this->entityManager->flush();
        }
        return $this->render('client/create.html.twig', ['form' => $form->createView()
        ]);
    }

    /**
     * @Route ("/client/{id}/edit", name="client.edit")
     */
    public function edit($id, Request $request)
    {
        $client = $this->clientRepository->find($id);
        if ($client === null) {
            throw $this->createNotFoundException("Client #{$id} does not exist.");
        }

        $form = $this->createForm(ClientType::class, $client);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Client $data */
            $data = $form->getData();

            $this->entityManager->persist($data);
            $this->entityManager->flush();

            return $this->redirect('/client');
        }

        return $this->render('client/create.html.twig', ['form' => $form->createView()
        ]);
    }

    /**
     * @Route ("/client/{id}/delete", name="client.delete")
     */
    public function delete($id)
    {
        $client = $this->clientRepository->find($id);
        $this->entityManager->remove($client);
        $this->entityManager->flush();
        return $this->redirect('/client');
    }

}

templates/client/create.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                {{ form_start(form) }}
                <div class="form-group">
                    {{ form_label(form.name) }}
                    <div class="form-control">
                        {{ form_widget(form.name, {attr: {class: 'form-control'}}) }}
                    </div>
                </div>
                {{ form_errors(form.name) }}
                <div class="form-group">
                    {{ form_label(form.gender) }}
                    <div class="form-control">
                        {{ form_widget(form.gender, {attr: {class: 'form-control'}}) }}
                    </div>
                </div>
                <div class="form-control">
                    {{ form_widget(form.save,  {attr: {class: 'form-control btn btn-success'}}) }}
                </div>
                {{ form_end(form) }}
            </div>
        </div>
    </div>
{% endblock %}

templates/client/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                <table class="table">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Name</th>
                        <th>Gender</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for client in clients %}
                        <tr>
                            <td>{{ client.id }}</td>
                            <td>{{ client.name }}</td>
                            <td>{{ client.genderString }}</td>
                            <td><a href="{{ path('client.edit', {id: client.id}) }}">Edit</a></td>
                            <td><a href="{{ path('client.delete', {id: client.id}) }}">Delete</a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-8 offset-2">
                <a class="btn btn-warning" href="{{ 'client/create' }}">Create client</a>
            </div>
        </div>
    </div>
{% endblock %}